services:
  homepage:
    container_name: homepage
    build: 
      context: ./
      dockerfile: ./docker/local/react/Dockerfile
    volumes:
      - ./client/src:/app/src
    ports:
      - 5173:5173
    networks:
        - main-nginx-net
    command: npm run dev

    
networks:
  main-nginx-net:
    external: true
