services:
  homepage:
    container_name: homepage
    build: 
      context: .
    volumes:
      - ./client/src:/app/src
    ports:
      - 5173:5173
    networks:
        - local-nginx-net
    command: npm run dev

    
networks:
  local-nginx-net:
    external: true
