services:
  homepage:
    container_name: homepage
    build: 
      context: .
    volumes:
      - ./client:/client
      - /client/node_modules/
    ports:
      - 5174:5173

    expose:
        - 5173
    networks:
        - local-nginx-net
    command: npm run dev

    
networks:
  local-nginx-net:
    external: true
