services:
  homepage:
    container_name: homepage
    build: 
      context: .
    volumes:
      - ./client:/client
      - /client/node_modules/
    ports:
      - 5174:5173

    expose:
        - 5173
    command: npm run dev

    
